name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build and run tests
      run: |
        cmake -Bbuild -H.
        cmake --build build
        cd build
        ./MyArduinoTests
