name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y build-essential

    - name: Install build dependencies (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install cmake
        brew install googletest

    - name: Install build dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake
        choco install visualstudio2019buildtools

    - name: Build and run tests
      run: |
        mkdir build
        cmake -Bbuild -H.
        cmake --build build
        cd build
        if ($env:CI_OS_NAME -eq "Windows") {
          .\MyArduinoTests
        } else {
          ./MyArduinoTests
        }
      env:
        CI_OS_NAME: ${{ matrix.os }}
