name: Run Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/run-cmake@v1

    - name: Build project
      run: |
        make clean
        make

    - name: Run tests
      run: ./run_tests.sh
