name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./build/MyArduinoTests.exe
          else
            ./build/MyArduinoTests
          fi
      
    
