name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download yq binary
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.18.2/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          
      - name: Test
        uses: arduino/cpp-test-action@v1
        with:
          source-path: .  
          build-path: build  

